Minimal mode app booting
catalpainternational/canoe pull request #274
Opened 2020-10-30 21:06 UTC by boerwastaken

Closes #269 

### Related
Comes on top of #268 and #271 . Those can be examined and merged first, or disregarded and treated as part of this PR. But it makes more sense to examine & merge those separately & first,  because they address separate issues (bugs) that have no direct relation to the #269 Lean booting goal (but I needed to fix them, because crash.). They're bugfixes, good to have regardless of this here PR.

***Note that there are no user-visible changes for existing use cases***. I'm trying to do the minimal, and the minimal can be improved upon. Especially keep in mind that yes, while `U+1f638` is debatable, no user and probably no dev will see it in the user interface, at least not until they mess about a bunch with their devtools. Hum-ing and hehm-ing about `U+1f638` is not what I want this PR and its reviews to be about.

### What does it do

It makes it so that Canoe can boot with just a `Serviceworker` and some `Cache`s installed. This makes it easier for an eventual Appelflap state transfer implementation to take care of, well, transferring state, as it doesn't have to set project-specific cookies/localStorage/IDB stuff in project-specific ways just to poke things into a state that the webapp doesn't crash with or does something weird with. It should be the webapp's responsibility to be able to bootstrap itself from a minimal state, reinitializing things where necessary. And now Canoe can! Hurray again!

In the process, out of necessity, I also made the "are we authenticated" evidence-based rather than belief-based.
It used to be based solely on presence or absence of a cookie with name "Token", disregarding the payload.
And even if it would be verifying the payload (which it can't, because currently Canoe's tokens are HMAC based rather than signature based!), it wouldn't know whether the server hasn't rotated keys or disabled the user. Evidence-based is just better.

In a nutshell:
- Don't assume presence of a cookie with name "Token" means we're authenticated (and will always be authenticated)
- Don't set the user stuck on a login screen when no such "Token" cookie is available — the user might be offline, unable to login, but might want to interact with the learning content that's available from the cache.
- Track authentication status. We're authenticated until proven otherwise, and once proven deauthenticated, we're deauthenticated until we've logged in again.

### Testing

1. Load the webapp on a clean profile as usual
2. Log in to fill your caches with e-learning goodness
3. Set yourself to offline (via network tab of devtools)
4. Play around with deleting any/some/all of Cookies, IDB, LocalStorage items, ... But not Caches, or the Serviceworker, duh.
5. For any of the operations of step 4, witness that the webapp still boots (ctrl-L, enter)
6. Hop online, load the webapp (ctrl-L, enter)
7. If you had deleted the cookie, you should now see a login screen - that you didn't see when you were offline, which is good, because it's no good presenting a login screen to a user who's offline!

### Possible further improvements

#### Deauthentication detection

Currently the deauthentication-detection piggybacks on the requests to various backend-pages ("actions", lesson pages. I think). 

Nothing wrong with that, but I'm quite unfamiliar with this project, there may be better candidates that are more regularly polled. I don't know, is there anything that is ever polled again after boot? What if there are content updates? Is the user expected to refresh the page regularly or something?

In Gather I poll an endpoint on an interval, and this *invites* the user to re-login if it turns out that the user isn't anymore —
rather than dumping them to a login screen that can't be bypassed. Especially with intermittent connectivity, an invitation is the better approach — while there is a network available at the time of unauthenticatedness detection, there might not be one by the time the user walks back to their browser/tablet! So the poll-and-invite approach is clearly superior in that respect, especially if the invitation to re-login is automatically detracted when the network goes away (it's a stretch, but it'd be really good UX). In Gather, the re-login invitation is canceled if by some magic the authentication succeeds again, which is also nice. But in this app, with this PR, once a deauthentication is detected, you'll be dumped to the login screen (on reload anyway) with no way to restore access to the learning materials (that may actually be right there, on the device! how frustrating! locked out by your own devices! At least good oldfashioned books don't pull that trick on you!) other than having a) internet b) a valid login . For remote no-internet scenarios that's clearly undesirable. To fix that we'll need a wider discussion. I'd suggest a local-only-mode one-button on the login screen that just lets you get on with what you have on the device.

#### Auto-guest-login

Currently, as I'm just trying to do minimally invasive stuff to get to the desired goal of lean boots, no super smart behaviour is set up. But I saw that there was something like a "guest mode" on haroman.tl. On a cold boot of the webapp, the user could be offered to use the guest account instead of the rather minimal anonymous mode that's currently set up with this PR.

2020-10-30 21:18 UTC, boerwastaken commented on src/js/AuthenticationUtilities.js
> -        throw error;
catch and throw it again! and again! and then some more! :smile_cat:

2020-11-03 06:54 UTC, PeteCoward commented on src/js/AuthenticationUtilities.js
> +    return found_cookie? found_cookie.substring(found_cookie.indexOf('=') + 1): null
```suggestion
    return found_cookie ? found_cookie.substring(found_cookie.indexOf('=') + 1) : null
```

2020-11-03 06:56 UTC, PeteCoward commented on src/js/AuthenticationUtilities.js
> +export const setIsAuthed = (somebool) => {
camelCase
```suggestion
export const setIsAuthed = (someBool) => {
```

2020-11-03 06:57 UTC, PeteCoward commented on src/js/AuthenticationUtilities.js
> +    return localStorage.setItem(USER_IS_AUTHED_STORAGE_KEY, Boolean(somebool));
camelCase
```suggestion
    return localStorage.setItem(USER_IS_AUTHED_STORAGE_KEY, Boolean(someBool));
```

2020-11-03 07:00 UTC, PeteCoward commented on src/js/AuthenticationUtilities.js
> +const ANONYMOUS_USER = "😸";  // U+1f638 Grinning cat face with smiling eyes
I think for safety we should avoid the risk of showing people grinning cat emoji's by either setting it to something more descriptive, or not returning it from the getUsername function

2020-11-03 07:09 UTC, PeteCoward commented on src/js/AuthenticationUtilities.js
> +const ANONYMOUS_USER = "😸";  // U+1f638 Grinning cat face with smiling eyes
I know, should never see it, but developers do funny things, and if they do I'd rather it was descriptive

2020-11-03 11:49 UTC, boerwastaken commented on src/js/AuthenticationUtilities.js
> +const ANONYMOUS_USER = "😸";  // U+1f638 Grinning cat face with smiling eyes
I first tried returning an empty string but that makes Canoe crash.
Ideally it'd return `null` when there isn't one, it's the most appropriate response, but the callers need to be able to handle that.

2020-11-03 15:31 UTC, boerwastaken commented on src/js/AuthenticationUtilities.js
> +const ANONYMOUS_USER = "😸";  // U+1f638 Grinning cat face with smiling eyes
Now, absense of any stored username makes you a guest, coalescing the no-user case with the guest-user case. No more cats.

2020-11-03 20:52 UTC, sandroroux requested changes
@boerwastaken, I don't quite follow this PR's goal. If the user lacks indexedDB and `localStorage` data, we can't guarantee the app will work correctly, so we want the app to crash gracefully (which it doesn't right now, I see).

Some new bugs arise if we change this assumption. Let's say I delete `username` from local storage: with your change, I'm switched to "guest" mode. Even though I'm a guest, some of my user account's information carries forward to guest mode:
* my username's `userId` and `userGroups` still submits with analytics calls.
* my user name's completion data carries into the guest mode's course materials.

These aren't new bugs, but different bugs, so it's not a fault of your fix. I still think we should ask whether this approach is the best. Can we discuss why Appelflap needs our app's assumptions to change?

2020-11-03 20:52 UTC, sandroroux commented on src/js/AuthenticationUtilities.js
> +    setIsAuthed(false);
Shouldn't this be unnecessary? If the user logged out, there will be no `USER_IS_AUTHED_STORAGE_KEY` in local storage. `localStorage.getItem(USER_IS_AUTHED_STORAGE_KEY)` would return `null`.

2020-11-03 20:52 UTC, sandroroux commented on src/js/AuthenticationUtilities.js
> +    return (auth_status_denoted === null || auth_status_denoted === "true");
Why does the lack of a `USER_IS_AUTHED_STORAGE_KEY` imply that the user is logged in? Am I misunderstanding this conditional?

2020-11-04 07:20 UTC, boerwastaken commented on src/js/AuthenticationUtilities.js
> +    return (auth_status_denoted === null || auth_status_denoted === "true");
Because logged out state is innocent until proven guilty, so to speak.
If it has not been witnessed that a user is logged out, they're not.
Flipping this around (guilty until proven innocent, so to speak), Canoe would dump the user to a login screen on a lean offline boot, which is undesirable. Hence, innocent until proven guilty.

There's certainly smarter things that Canoe could do in this case, some of which I hint at in the PR under *Possible further improvements*. But I don't want to change too much of Canoe right now.

2020-11-04 07:31 UTC, boerwastaken commented on src/js/AuthenticationUtilities.js
> +    setIsAuthed(false);
> If the user logged out, there will be no USER_IS_AUTHED_STORAGE_KEY in local storage.

Is that so? Where is the code which removes this localstorage item when the user logs out?

If the user explicitly logs out then we don't want to second-guess that. As explained below, unless unauthedness is proven (which can't happen offline), the user is presumed logged in, so removing explicitly setting `USER_IS_AUTHED_STORAGE_KEY` to false to reflect explicit user intent is the right thing to do currently. There's certainly improvements possible, as I write in the PR under *Possible further improvements*. But that's outside of the scope of what I'm trying to get working here.

2020-11-04 10:56 UTC, boerwastaken commented
> I don't quite follow this PR's goal.

Aight, I've expanded #269 to give more context, you may have been out of the loop. It's an RFC now, so if you need more clarification or have alternate ideas, or comments, please put them in there!


> If the user lacks indexedDB and localStorage data, we can't guarantee the app will work correctly, so we want the app to crash gracefully (which it doesn't right now, I see).

I don't think anyone's arguing that Canoe should be able to survive and repair arbitrary damage to IDB and localStorage data.

What I would like to get to is at least a well-defined minimal bundle of offline state necessary for Canoe to a) not crash and hopefully b) to do some more interesting things than just dump the user to a login screen. This PR does the minimal to accomplish a) and b).
As for "well-defined minimal bundle of offline state", it turns out that with little poking Canoe can reach the ideal minimal state of just-a-serviceworker-with-just-some-caches, as outlined in #269. If more state transfer, beyond Caches and Serviceworkers, is required, then that can be argued for in #269.

> Some new bugs arise if we change this assumption. Let's say I delete username from local storage: with your change, I'm switched to "guest" mode. Even though I'm a guest, some of my user account's information carries forward to guest mode:
>
>    my username's userId and userGroups still submits with analytics calls.
>    my user name's completion data carries into the guest mode's course materials.

Though it's fun seeing what happens when individual items are removed (applying arbitrary damage), and encouring to see that no permutation of removals make Canoe crash anymore now, robustness in the face of arbitrary damage is not the goal; "arbitrary damage can happen" has never been the assumption, and I don't think it'll ever need to be.

The much less wild assumption that should be worked with from now on is that any serviceworkers or caches are intact, and localStorage/IDB/cookies are either all missing, or intact. See #269 for the considerations from which this follows, and discuss there.

This PR is mostly bug fixes, and introduces no new behaviour for all existing deployment scenarios. It's a starting point so we have Canoe in a state where we can transplant its innards without the receiving vessel crashing.
More thoughtful handling of guest mode is certainly something worthwhile to have in Canoe. Leaving the user stranded on a login screen and locking them out from their study materials until they've found internet and succeed to login is not good style. But those are not issues that need to be addressed *right now*.

2020-11-04 18:45 UTC, sandroroux approved these changes

2020-11-04 18:53 UTC, merged