Appelflap cache api
catalpainternational/canoe pull request #305
Opened 2020-12-14 08:13 UTC by md8n

Implements the low level calls to Appelflap, as per Wicher's documentation.

2020-12-15 21:44 UTC, boerwastaken commented on src/ts/AppelflapConnect.ts
>              return "Nope, that's not OK";
if you're going to return a string (is that better than raising an exception?), wouldn't it be more helpful to template in the response code? with a reference to the API docs perhaps, so that it's more clear what's awry.

I'm not sure that choosing an error path (whatever form it takes) for `!response.ok` is the right thing to do. Perhaps the code wants to probe for a certain cache publication, in which case a 404 should be usefully distinguishable from a 500.

2020-12-15 23:56 UTC, md8n commented on src/ts/AppelflapConnect.ts
>              return "Nope, that's not OK";
@boerwastaken - this is just placeholder code until we figure out what's really required for this interaction.

In general for JS it's preferable to not throw an exception, unless something 'exceptional' actually took place.  However, because we're still figuring things out I expect that some cases may warrant an exception.

2020-12-16 03:18 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +        const weHazAuthorization = false;
pleaz no text speak
```suggestion
        const weHaveAuthorization = false;
```

2020-12-16 03:20 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +                return await response.text();
which of the appelflap methods requires text return?

2020-12-16 03:21 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +                return await response.text();
oh i see from below. Not sure why though, could we say appelflap always returns json, and any text body that is not json is swallowed or errored

2020-12-16 04:05 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +                : ({} as RequestInit);
if won don't need auth, or we don't have a `commandInit` passed, or our init just specifies GET
then use `undefined`
else use `commandInit` if it exists otherwise an empty RequestInit

Took me a while to work that out :) not a big fan of chained ternary ops

1. why not just use the init if it's passed, I don't see the need to check if just a GET.
2. if not `weHazAuthorization` this would use `undefined`, totally ignoring `commandInit` so unauthed POSTs would not work as expected

2020-12-16 04:36 UTC, PeteCoward commented on src/ts/Types/CacheTypes.ts
> +    webOrigin: string;
what is webOrigin for?

2020-12-16 04:39 UTC, PeteCoward commented on src/ts/CachePublish.ts
> +        return JSON.parse(publicationList) as TPublications;
`afc.getPublications()` does not specify type so defaults to 'json' type, so `afc.perform..` parses the return already, then you parse again here

2020-12-16 04:41 UTC, PeteCoward commented on src/ts/Types/CacheTypes.ts
> +    webOrigin: string;
oh it was required in Wicher's api, i get it. Might be best to make clear it is a domain if so, not a full Uri path

2020-12-16 04:49 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
this method actually gets headers not sets them

2020-12-16 04:50 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
it also totally hides and invisibly "corrects" anyone calling it wrongly

2020-12-16 04:52 UTC, PeteCoward requested changes
A bit complex for my taste in places, but basically ok, but please check my reasoning for the comments and respond.
If I am correct changes are needed

2020-12-16 04:53 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +        const weHazAuthorization = false;
`requiresAuthentication` might be better or just don't code it until you need it ;)

2020-12-16 05:20 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +        const weHazAuthorization = false;
I put that in there precisely as a flag that we 'need' authorization.

2020-12-16 05:21 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +                return await response.text();
Some of the Appelflap returns are just simply human readable text response.  This just ensures that the text gets passed back in such cases.

2020-12-16 05:21 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +                : ({} as RequestInit);
I have a fix for this, that I've been testing with in the new unit tests.

2020-12-16 05:22 UTC, md8n commented on src/ts/Types/CacheTypes.ts
> +    webOrigin: string;
I stuck with Wicher's terms for the moment.  But getting these into definitions like this makes it really easy to change them later.

2020-12-16 05:23 UTC, md8n commented on src/ts/CachePublish.ts
> +        return JSON.parse(publicationList) as TPublications;
I think you may be right - in which case I have to type the return better.
I'm still working towards some of these via the unit tests

2020-12-16 05:25 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
It sets the headers for the fetch call based on what's passed in.
It is very deliberate that it takes total responsibility for these values once they've been passed to it.  I'll add more info to its JSDocs header to make that absolutely clear

2020-12-17 03:59 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
it returns an object that you use to set headers in a different place, but this method is badly named.
My comment about hiding bad values, was not to say that that behaviour was not documented, but that that behaviour is a bad idea.
Better to fail, so we see it.

2020-12-17 04:03 UTC, PeteCoward commented on src/ts/AppelflapConnect.ts
> +            (commandInit && JSON.stringify(commandInit) !== '{"method":"GET"}');
I mentioned before but the comment appear to have disappeared. What is the motivation behind trying to avoid using a RequestInit?
Why not just create an empty one if it's not passed and carry on?

2020-12-17 04:35 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +            (commandInit && JSON.stringify(commandInit) !== '{"method":"GET"}');
because `fetch` wants the `RequestInit` as `undefined` if the anticipated set of values should be what's considered as the defaults.
So I test if there's anything that is not considered a default value and only set up a `RequestInit` in those circumstances.

2020-12-17 04:40 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
> Better to fail, so we see it.
Not in every case - I think as software developers we focus too much on failing things that we could simply and reasonably just 'fix'.

- Where we can't make reasonable assumptions - fail
- Where we can make reasonable assumptions - fix

2020-12-17 07:30 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +    private setVersionHeaders = (
I've changed this to throw an exception.  I don't like it, but I've done it.

2020-12-17 07:31 UTC, md8n commented on src/ts/AppelflapConnect.ts
>              return "Nope, that's not OK";
I've already made changes for this that will be in the first significant unit testing :pr:

2020-12-18 00:27 UTC, md8n commented on src/ts/AppelflapConnect.ts
> +            (commandInit && JSON.stringify(commandInit) !== '{"method":"GET"}');
OK - I tested it, and fetch (at least node-fetch) doesn't care.  So I simplified the requestInitRequired test.

2020-12-18 01:36 UTC, merged