Clean up lessons
catalpainternational/canoe pull request #346
Opened 2021-01-13 20:09 UTC by katevoss

Closes https://github.com/catalpainternational/canoe/issues/342

More to come
🤞🏻 I didn't break anything

2021-01-13 23:06 UTC, sandroroux commented on src/riot/Lesson/LessonFeedback.riot.html
> +            clickedThisLessonIs(rating) {
If you go down this route, I'd enforce that `rating` is `"bad"`, `"fine"`, or `"great"`.

Something like:
```js
if (!["bad", "fine", "great"].includes(rating)) {
    throw Error('You must call this with a rating of "bad", "fine", or "great"');
}
```

2021-01-13 23:20 UTC, sandroroux commented on src/riot/Lesson/LessonComplete.riot.html
>                      </div>
To me, this screen looks wonky. Originally, the confetti was in the top-left corner, and the text and buttons were centered(?).
<img width="200" alt="image" src="https://user-images.githubusercontent.com/4751297/104521712-71267580-55cb-11eb-885b-385a0b0311d4.png">

The confetti looks so alone.

2021-01-13 23:21 UTC, sandroroux requested changes
Looks good! I'd check the feedback-submission code's parameters and find a home for LessonComplete's lonely confetti.

2021-01-14 00:48 UTC, katevoss commented on src/riot/Lesson/LessonComplete.riot.html
>                      </div>
The poor confetti 🎊 I think what happened is that the report card svg disappeared, and in the course of cleaning up `_lesson.scss` I decided to just put the confetti on this page. I'll make the confetti be less sad and alone.

2021-01-14 02:13 UTC, katevoss commented
@sandroroux I got a little carried away and made more changes, but I addressed your feedback too.

2021-01-14 17:09 UTC, sandroroux approved these changes

2021-01-14 17:39 UTC, merged