Add identity reduck
catalpainternational/canoe pull request #370
Opened 2021-01-25 08:23 UTC by PeteCoward

WIP

2021-01-26 06:47 UTC, PeteCoward commented on src/app.js
> +}
intention is for this to be a big list of `initialiszeThis` function calls

2021-01-28 01:30 UTC, md8n approved these changes

2021-01-28 01:30 UTC, md8n commented on src/riot/Screens/Login.riot.html
> +
Just delete this empty line - and then it's one less file in this :pr:

2021-01-28 01:30 UTC, md8n commented on src/riot/App.riot.html
> +        export default App
Really nice work - thanks

2021-01-28 01:35 UTC, PeteCoward commented on src/riot/Screens/Login.riot.html
> +
whoops!

2021-01-28 02:18 UTC, md8n requested changes

2021-01-28 02:18 UTC, md8n commented on src/riot/App.riot.html
> -                    contentType: pageModel,
Setting this value `contentType` into the `state` is absolutely necessary for the `Sync` page to actually show up.  This is the output from the call to `getWagtailPageModelName` above

2021-01-28 02:37 UTC, md8n approved these changes

2021-01-28 02:44 UTC, PeteCoward commented on src/riot/Screens/Login.riot.html
> +
```suggestion
```

2021-01-28 03:27 UTC, md8n commented
OK - actually approved now - feel free to merge in

2021-01-28 04:25 UTC, merged