389 feedback screen visual design qa
catalpainternational/canoe pull request #414
Opened 2021-02-11 04:30 UTC by megganeturner

Addresses feedback in #389:
- remove sun icon & add new subtitle 'Let us know how you feel'
- centre the icons in the buttons, add labels, and add active state
- tweaks to the card such as border-radius, 'x' colour, `<p>` colour

I'm still waiting on a few translations - if I get them by EOD I'll update this branch, otherwise I can add them to my next branch (which looks at the feedback confirmation screen, so closely related)

![Screen Shot 2021-02-11 at 3 02 59 pm](https://user-images.githubusercontent.com/12974326/107602441-a7fcb380-6c7d-11eb-9d2a-1bd5213f9d61.png)
![Screen Shot 2021-02-11 at 3 03 23 pm](https://user-images.githubusercontent.com/12974326/107602444-aa5f0d80-6c7d-11eb-9d18-129140cb6139.png)

2021-02-11 15:32 UTC, katevoss requested changes
Looks good, a few things to fix but should be fast.

2021-02-11 15:32 UTC, katevoss commented on src/riot/Lesson/LessonFeedback.riot.html
>                  <h2>{ TRANSLATIONS.feedback() }</h2>
The `TRANSLATIONS.feedback()` is no longer used in the modal so you can remove it from the `TRANSLATIONS` object in line 53.

2021-02-11 15:32 UTC, katevoss commented on src/scss/_lesson.scss
> +    // .feedback-icon {
You can remove the `.feedback-icon` class as it's not used anywhere else. Again I'm not sure why you commented it out but this whole section can be removed.

2021-02-11 15:32 UTC, katevoss commented on src/scss/_lesson.scss
> +            &:active {
I don't think these styles appear, the smiley faces disappear as soon as you click one so there's no `:active` state.

2021-02-11 23:04 UTC, megganeturner commented on src/scss/_lesson.scss
> +            &:active {
Oh true! I've just looked more closely at the design and can see the flow is actually `click an option (it highlights)` --> `click 'submit feedback' button` --> `confirmation screen`. I can work through this functionality today

2021-02-12 00:25 UTC, megganeturner commented
Okay I've update the flow so that you can 'submit feedback' - I've kept the 'Maybe later' button in, as I feel that's a better user experience, but happy to remove it!

![Screen Shot 2021-02-12 at 11 20 08 am](https://user-images.githubusercontent.com/12974326/107716076-b225bd00-6d24-11eb-96ab-26b98ab353cd.png)
![Screen Shot 2021-02-12 at 11 20 24 am](https://user-images.githubusercontent.com/12974326/107716077-b4881700-6d24-11eb-841f-85d43c84ae48.png)

2021-02-12 02:28 UTC, katevoss requested changes
One last issue with the buttons showing their colors. I'm good with having the "submit" and "Maybe Later" buttons, but let's make the "Submit" a primary button.

2021-02-12 02:28 UTC, katevoss commented on src/riot/Lesson/LessonFeedback.riot.html
> +            <template if="{state.activeSelection}">
#### 1. When I click the button I see the `:active` style but when I finish "clicking", it reverts to the not `:active`. It should stay "active" once I have selected it.

#### 2. When this button appears, it shifts the content up (more noticable on wide and tall screens)
initial:
<img src="https://user-images.githubusercontent.com/2395211/107723522-540ac280-6caf-11eb-86ef-270f025e6a79.png" width="350">

shifted:
<img src="https://user-images.githubusercontent.com/2395211/107723506-4b19f100-6caf-11eb-8722-c3102d2e907f.png" width="350">

2021-02-12 03:06 UTC, megganeturner commented on src/riot/Lesson/LessonFeedback.riot.html
> +            <template if="{state.activeSelection}">
Number 1 was caused by a smol merge issue - I'd changed `:active` to `.active`, but it had been overwritten. This is resolved now.

Number 2 has also been resolved, good pickup:
![Screen Shot 2021-02-12 at 2 03 41 pm](https://user-images.githubusercontent.com/12974326/107725894-734f3180-6d3b-11eb-8e72-6e96a0b22257.png)
![Screen Shot 2021-02-12 at 2 03 49 pm](https://user-images.githubusercontent.com/12974326/107725897-75b18b80-6d3b-11eb-96cd-082cadc22d76.png)

2021-02-12 14:02 UTC, katevoss approved these changes

2021-02-12 14:03 UTC, merged