#488: Submits Lesson Feedback to User Actions
catalpainternational/canoe pull request #492
Opened 2021-03-01 20:41 UTC by sandroroux

Closes catalpainternational/canoe#488.

2021-03-02 00:21 UTC, PeteCoward commented on src/riot/Lesson/LessonFeedback.riot.html
> +        <button class="btn-secondary" onclick="{clickedNoThanks}">
Can you set format only changed lines in visual studio please?
Especially while we have two feature branches in play, these non-change changes cause conflict headaches if someone changes one thing in these lines in the other branch

2021-03-02 00:22 UTC, PeteCoward commented on src/sw.js
> +registerRoute(
Any actual changes in this file?

2021-03-02 16:59 UTC, sandroroux commented on src/riot/Lesson/LessonFeedback.riot.html
> +        <button class="btn-secondary" onclick="{clickedNoThanks}">
Absolutely.

2021-03-02 17:00 UTC, sandroroux commented on src/sw.js
> +registerRoute(
Nope. I disabled workbox logging and removed the statement. Must have `prettier`ed the file on the way out.

2021-03-08 05:50 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +        const response = await postFeedback(feedback);
what is the behaviour if a feedback is posted, received by the server, but we do not get the ok response, it does not get deleted, then we try again?

2021-03-08 21:09 UTC, sandroroux commented on src/js/Telemetry/index.js
> +        const response = await postFeedback(feedback);
That's my understanding.

Can the server create a user action and return a not-ok response?

2021-03-09 02:26 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +        const response = await postFeedback(feedback);
No, but the reply could be lost in the tubes on the way back.
I can't remember if the backend would error on that second attempt, I think it would due to a uuid clash, and then not return OK, therefore repeating for ever and ever :)

2021-03-09 02:26 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +        const response = await postFeedback(feedback);
No, but the reply could be lost in the tubes on the way back.
I can't remember if the backend would error on that second attempt, I think it would due to a uuid clash, and then not return OK, therefore repeating for ever and ever :)

2021-03-10 16:27 UTC, sandroroux commented on src/js/Telemetry/index.js
> +        const response = await postFeedback(feedback);
I'll look into this. Thanks for describing that.

2021-03-16 00:07 UTC, sandroroux commented
@PeteCoward, I tried to handle the network errors. My approach feels a little loose. Let me know what you think.

2021-03-16 01:39 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +    }
not sure how much point there is in a catch with just a throw inside it.
If you want to suppress the error, then catch but do not throw.
If you want to raise the error, just don't try.. catch

2021-03-16 01:50 UTC, sandroroux commented on src/js/Telemetry/index.js
> +    }
I think it's a code legibility thing. I'm basically saying, "this code throws, but I'm not interested in catching here. I'll pass it up to whatever uses me."

2021-03-16 17:53 UTC, sandroroux commented on src/js/Telemetry/index.js
> +    }
@PeteCoward, see here too:
https://stackoverflow.com/a/11853583

2021-03-18 03:54 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +    }
from that link
> You catch an exception when you have something to do with it.

only the network error is an expected error here, and we know it might happen.
We also know that in theory not ok requests could occur.

If both those cases need to be handled in the same way we should raise a single fetch failed error in both cases to inform the calling code ( or catch the error and return a result if preferred )

The code as is just looks half implemented, and uglier and equal to no catching at all.

2021-03-18 03:56 UTC, PeteCoward requested changes
This seems to have changes not related to the task
- why delete favicon.svg?
- why change serviceworker code at all ( you have added a `ROUTES_FOR_REGISTRATION.images` route duplication )

2021-03-23 00:26 UTC, sandroroux commented
@PeteCoward:
* favicon.svg throws an error that blocks yarn's build process.
* The service worker changes are an unintentional merge mistake.

I'll revert the service worker changes. Have you run into the favicon errors?

2021-03-24 18:12 UTC, sandroroux commented on src/js/Telemetry/index.js
> +    }
I've read through your comment and am going to have another go at this.

To start, I built my approach using [this](https://medium.com/to-err-is-aaron/detect-network-failures-when-using-fetch-40a53d56e36) article. (FYI, the article covers errors much more exhaustively than my code).

If I understand your point correctly, I want to treat three cases separately:
* a 400-range response will return a response object;
* a 500-range response will throw an error;
* a network failure will throw an error.

My strategy is to only save my local copy when the network fails. In other cases, I'll delete my local copy. The way that breaks down is:
* If the response is 200 (`response.ok === true`), I will delete my local copy. The server has the entry, so the local copy is unneeded.
* If the response is 400 (`response.ok === false`), I will delete my local copy. The local copy is probably malformed. To prevent repeat 400s, I'll delete my local copy, but I'll log the not-okay.
* If the network fails (`fetch` throws an exception), I will try the fetch again on the next poll. The network is spotty, so I should persist the upload until it succeeds or 500s (because of a double-entry error, for example).
* If the server throws a 500 (`fetch` throws an exception), I will delete my local copy. A server bug means we'll lose feedback data inadvertantly. Hopefully, we'd notice the sentry errors before too much data loss. If a double-entry error occurs, we will delete the local copy and the UUID clash will disappear.

2021-03-24 23:54 UTC, PeteCoward commented
> * favicon.svg throws an error that blocks yarn's build process.

no

2021-03-24 23:57 UTC, PeteCoward commented on src/js/Telemetry/index.js
> +    }
how does the server respond when you throw up a duplicate? can we stop that 500ing.
Expecting 500s is bad :)

2021-03-25 22:28 UTC, sandroroux commented on src/js/Telemetry/index.js
> +    }
Good point. Here's [a back-end PR](https://github.com/catalpainternational/canoe-backend/pull/130) that turns UUID errors into 400s.

2021-03-29 14:13 UTC, sandroroux commented on src/js/Telemetry/index.js
> +    }
Updates.

Now, that back-end PR returns 201s when devs double UUIDS.

Since my earlier comments, I changed the algorithm. Here's the current approach:
* If the response is 200 (response.ok === true), I'll delete my local copy. The server has the entry, so the local copy is unneeded.
* If the response is 400 (response.ok === false), I throw the error. The local copy is probably malformed. The error may signal a bug in feedback-submitting code, so I want the developer to know about it.
* If the network fails (fetch throws an exception), I'll try the fetch again on the next poll. Since the network is spotty, I repeat the upload until it succeeds.
* If the server returns a 500 (fetch throws an exception), I throw the error. A 500 may signal a server issue that I want the developer to know.

2021-03-31 03:44 UTC, merged