fix bad conflict resolution merge
catalpainternational/canoe pull request #500
Opened 2021-03-05 02:30 UTC by PeteCoward

2021-03-05 06:38 UTC, md8n approved these changes

2021-03-05 06:49 UTC, PeteCoward commented
leaving this open for @katevoss to see in her morning, please merge if ok Kate

2021-03-05 18:17 UTC, katevoss requested changes
The resource articles don't load so this isn't mergeable because we are deploying FT-Offlining so it can't have broken things. If we can have broken things on FT-Offlining then we can merge and make another PR to fix articles.

2021-03-05 18:17 UTC, katevoss commented on src/riot/Lesson/LessonContent.riot.html
> +        <template if="{props.resourceId === 'resources'}" each="{card in state.cards}">
The resource article still doesn't load because the data shape for a ResourcePage is different from a LessonPage. I can't find a simple fix to make it work, they seem to be very different and there are a lot of ways that they're intertwined. I think the logic and styling for Resource Articles needs to be separated from LessonContent, either on this PR or on one soon.

2021-03-08 00:47 UTC, PeteCoward commented on src/riot/Lesson/LessonContent.riot.html
> +        <template if="{props.resourceId === 'resources'}" each="{card in state.cards}">
We should stop the resources page using LessonContent I think

2021-03-08 05:44 UTC, PeteCoward commented
My preference would be to merge this now, as it looks like lesson content is working.
Then assign someone ( or me ) to fix resource content, preferably by disassociating it form the components used to render lessons

2021-03-08 05:45 UTC, merged