WIP 472 hero image implementation & 491 offline capability
catalpainternational/canoe pull request #501
Opened 2021-03-05 05:42 UTC by megganeturner

Draft status until Andy gets new stock images over to me :)

Addresses #472 & #491: implements images for cards, and adds in offline capability.

#472:
following on from Peter's changes in the backend (https://github.com/catalpainternational/canoe-backend/pull/99):
- replaces `<span>` with `background-image` with an `<img>` tag
- if a card has a value for the `card_image_url` attribute, we pass it through to the `<Card>` component and render it
- if a card doesn't have a value for `card_image_url` attribute, we display a fallback image
- pass a `cardType` prop to the `<Card>` component to dynamically render fallback image
- append the fallback image as a queryParam to the imageUrl as `?cardFallbackImage={}` for offlining stuff

#491:
Conditions of satisfaction:
- [x] when offline and card images can't be accessed card images fallback to the existing card defaults
- [x] once card images have been shown they are available offline

While I'm feeling a lot better about service workers in general they are still very much out of my comfort zone, so any feedback here is very welcome 😁 

- register a route to cache images with the `?cardFallbackImage=` query param attached, to cache to `card-images-cache`
- extend this route with a custom plugin, which defines the following callbacks:
&nbsp;&nbsp; - `fetchDidFail` - "Called when a network request fails, most likely due to a NetworkError. Note that this does not get called when a response with an error status, like 404 Not Found, is returned from the network."
&nbsp;&nbsp; - `fetchDidSucceed` - "Called when a network request is successful, regardless of what the HTTP status is of the response."
&nbsp;&nbsp; - `handlerDidError` - "Called if the handler was unable to provide a valid response from any source."
- additionally, defining `setCatchHandler`, which "is triggered when any of the other routes fail to
generate a response." From what I can see, it seems to get fired when the server is offline

All of these are doing the same thing: providing the fallback url based on the queryParams on the image url. This may be overkill, but some of them only get called in certain situations and I think this covers all our bases.

I'll add images to a couple of courses & lessons in wagtail. To test the image fallback, you can change line 36 of `Components/Card.riot.html` to something like
`return this.props.imageUrl ? `not/an/image.png?cardImageFallback=${fallbackImg}` : fallbackImg;`

Relevant documentation:
- https://developers.google.com/web/tools/workbox/guides/using-plugins?hl=en#custom_plugins
- https://developers.google.com/web/tools/workbox/guides/advanced-recipes#comprehensive_fallbacks

2021-03-05 18:53 UTC, katevoss reviewed
I haven't looked at the sw stuff yet but the riot stuff looks good so far 👍🏻 

Sometimes I get these img not found errors, I'll look more into it next week
![image](https://user-images.githubusercontent.com/2395211/110160477-11be3800-7dba-11eb-83ad-0bf15f673ff5.png)

2021-03-05 18:53 UTC, katevoss commented on src/riot/Components/Card.riot.html
> +                return this.props.imageUrl ? `${getMediaUrl(this.props.imageUrl)}?cardImageFallback=${fallbackImg}` : fallbackImg;
```suggestion
                return this.props.imageUrl
                    ? `${getMediaUrl(this.props.imageUrl)}?cardImageFallback=${fallbackImg}`
                    : fallbackImg;
```

2021-03-05 18:53 UTC, katevoss commented on src/riot/Components/Card.riot.html
> +            <img crossorigin="anonymous" src="{getCardImageUrl()}" class="card-hero-image">
```suggestion
            <img crossorigin="anonymous" src="{getCardImageUrl()}" class="card-hero-image" />
```

2021-03-08 02:20 UTC, PeteCoward reviewed
Why am i seeing stock_image_1.png here as empty files? Are they empty or an accidental add/commit?

2021-03-08 02:23 UTC, PeteCoward commented on src/sw.js
> +                maxAgeSeconds: 30 * 24 * 60 * 60,
Not sure these lines are wise! No need to expire based on number of entries or age

2021-03-08 02:24 UTC, PeteCoward reviewed
Why the move from named stock images to numbered ones?
Naming is helpful I think :)

2021-03-08 04:18 UTC, megganeturner commented
Hey @PeteCoward - if you click on the 'display rich diff' button you'll be able to see the images. They've also been given numbers as Andy requested they be randomised, rather than having 1 image for a course, another for a lesson etc.:

<img src="https://user-images.githubusercontent.com/12974326/110273542-ebe69c80-8020-11eb-928a-59288e840bf4.png" width="400">

2021-03-08 05:59 UTC, PeteCoward commented on src/sw.js
> -                maxEntries: 50,
oh dear this was a bad idea of mine!
`WorkboxError: You must define either config.maxEntries or config.maxAgeSecondsin workbox-expiration.Plugin.constructor`

2021-03-08 06:01 UTC, PeteCoward commented on src/sw.js
> -                maxEntries: 50,
I suggest we just set a large maxEntries

2021-03-08 06:06 UTC, megganeturner commented on src/sw.js
> -                maxEntries: 50,
Ah! That's my mistake for not testing again! Is 1000 too large? Not large enough?

2021-03-08 06:12 UTC, PeteCoward requested changes
I'm seeing requests to `/media//media/images/Triage_E_pJhasJq.2e16d0ba.fill-200x100-c50.format-jpeg_k7hJpfK.jpg` which always 404, and always show the fallback.
So the fallback is working, but the real image is not :)

2021-03-08 06:16 UTC, PeteCoward commented on src/sw.js
> -                maxEntries: 50,
maybe a maxAge equivalent to 5 years is better

2021-03-08 06:17 UTC, PeteCoward commented
Also we are caching the image with a number of different fallback urls as part of the key. This means we are storing the same image many times over. I'll pull and see if I can fix.

2021-03-08 07:05 UTC, megganeturner commented
After discussing with Pete, I've de-randomised the fallback images - we can discuss this with wider team at design-eng sync on Wednesday :)

I'll take a look at the 404 issue with  `/media//media/images/Triage_E_pJhasJq.2e16d0ba.fill-200x100-c50.format-jpeg_k7hJpfK.jpg` tomorrow morning!

2021-03-09 02:59 UTC, PeteCoward reviewed
Looks good, I'll test it once more...

2021-03-09 04:01 UTC, PeteCoward approved these changes

2021-03-09 04:02 UTC, merged