Feedback includes course name.
catalpainternational/canoe pull request #581
Opened 2021-03-31 19:08 UTC by sandroroux

2021-03-31 21:16 UTC, sandroroux commented on src/ts/Implementations/PublishableItem.ts
> +        // logger.log("using network for %s:%s", this.str, this.url);
@md8n Is there a way to disable these?

2021-03-31 22:32 UTC, PeteCoward commented on src/ts/Implementations/PublishableItem.ts
> +        // logger.log("using network for %s:%s", this.str, this.url);
Just jump into Logger, and disable all logs by commenting out one line.
I intended to add capability in Logger.ts to control them in config and runtime but had to swtich to doing something more targetted to real progress.
Being able to deploy to staging with listen this this named logger at this log level .
Being able to on production enter something in the console which sets those log level and name filters.

2021-03-31 22:36 UTC, PeteCoward requested changes
- add / use course id
- revert logger comment outs

2021-03-31 22:36 UTC, PeteCoward commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    course: courseName,
please use the Course id, not the name. The name can change.
Send the name if you want, but in the analysis views we should always use the pk to look up the name in a join

2021-03-31 22:36 UTC, PeteCoward commented on src/ts/Implementations/PublishableItem.ts
> +        // logger.log("using network for %s:%s", this.str, this.url);
Also, you can just set your log level filter in the dev tools to hide them. And set a filter on contents to filter for the ones you want to see.

2021-04-01 01:21 UTC, sandroroux commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    course: courseName,
I agree with the idea, but implementing the JOINs before I switch to hamahon may be tough. Let's chat about what my goal for this should be.

2021-04-01 02:51 UTC, PeteCoward commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    course: courseName,
for now, just add the id in here, then we can use either in the backend, and switch to the better method when we've worked out the sql required

2021-04-01 16:28 UTC, sandroroux commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    course: courseName,
Will do.

2021-04-01 19:38 UTC, sandroroux commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    course: courseName,
Done.

2021-04-05 23:20 UTC, PeteCoward commented on src/riot/Lesson/LessonContent.riot.html
> -        courseName="{props.lesson.course.title}"
in this situation we should just pass the lesson through, and access the attributes from inside the tag, not a problem fo now though

2021-05-03 03:22 UTC, PeteCoward approved these changes

2021-05-05 10:55 UTC, merged

2021-05-05 19:38 UTC, boerwastaken commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    lesson: lessonId,
on the backend, for analysis, we'd really like a page revision as the sole topic. No need for lessonId or courseId, as the backend can tell that from the page revision. It's not forbidden to leave them in though, if needed clientside.

2021-05-06 06:10 UTC, boerwastaken commented on src/riot/Lesson/LessonFeedback.riot.html
> +                    lesson: lessonId,
Does this end up in a post to the UserAction endpoint? On the backend, for analysis, we'd really like a page revision as the sole topic. No need for lessonId or courseId, as the backend can tell all that (and more, basically everything there is to know) from the page revision. It's not forbidden to leave them in though, if needed clientside.