Actions in redux
catalpainternational/canoe pull request #598
Opened 2021-04-14 07:16 UTC by PeteCoward

Still being tested...

- [ ] clicking through all the cards in a lesson, sets that lesson to complete
   - [ ]  the questions are stored for M&E ( this is slightly dumb as they are all correct )
- [ ] finishing the last lesson in a course completes the course too if there is no exam
- [ ] completing a pre-learning exam completes the course
- [ ] finishing a course exam but failing, does not complete the course
- [ ] passing a course exam does complete the course

Still being refactored for tidyness and naming

2021-04-14 07:44 UTC, PeteCoward commented on src/index.js
> +            window.location.reload();
passing true is a deprecated interface, not sure why it was there to begin with

2021-04-16 06:44 UTC, PeteCoward commented on src/riot/Lesson/TestMultipleAnswer.riot.html
> +                const storedAnswerData = this.getAnswer();
this is a candidate to move into the page ts code

2021-04-19 05:41 UTC, md8n requested changes

2021-04-19 05:41 UTC, md8n commented on src/ts/Implementations/Specific/Course.ts
> +import { persistExamScore } from "js/actions/ExamScores";
You need to add a typings file for this

2021-04-19 05:46 UTC, PeteCoward commented on src/ts/Implementations/Specific/Course.ts
> +import { persistExamScore } from "js/actions/ExamScores";
It's there, I had not pushed my latest

2021-04-19 05:53 UTC, PeteCoward commented
I pushed an error!

2021-04-19 05:57 UTC, md8n commented on src/ts/Implementations/Specific/Course.ts
> +import { persistExamScore } from "js/actions/ExamScores";
You're still missing that typings file

2021-04-19 06:24 UTC, md8n approved these changes

2021-04-21 06:00 UTC, megganeturner commented on src/ts/Implementations/Specific/Lesson.ts
> +        return this.storedData?.cards;
cards are nested in content, so this should be `return this.storedData?.content.cards;`

2021-04-22 00:14 UTC, PeteCoward commented on src/ts/Implementations/Specific/Lesson.ts
> +        return this.storedData?.cards;
not if you are running the accompanying backend pr catalpainternational/canoe-backend#148

2021-04-22 00:17 UTC, megganeturner commented on src/ts/Implementations/Specific/Lesson.ts
> +        return this.storedData?.cards;
Ah! 😱 Let me check all my other comments are still relevant 🤦🏼‍♀️

2021-04-22 00:26 UTC, megganeturner commented on src/ts/Implementations/Specific/Lesson.ts
> +        return this.storedData?.cards;
This one is fine, but everything else still stands (:

2021-04-22 00:57 UTC, PeteCoward commented on src/riot/Components/Card.riot.html
>                  return getCardImageUrl(this.props.link || this.props.contentItem.id, this.props.imageUrl);
see [Fix card images](https://github.com/catalpainternational/canoe/pull/598/commits/f4c30b5110f524a6bd1353e7c5670182e4c821ff)

2021-04-22 00:57 UTC, PeteCoward commented on src/riot/Lesson/ExamResults.riot.html
> +        <template if="{ course.examType !== 'prelearning' }">
see [fix exam results](https://github.com/catalpainternational/canoe/pull/598/commits/c7d4be2556e02993aa9d8644e9ee8e5a7b6d4846)

2021-04-22 00:58 UTC, PeteCoward commented on src/riot/Lesson/TestPopupModal.riot.html
> +                clearPageTestAnswers(this.lesson.id);
see fix t[est popup modal](https://github.com/catalpainternational/canoe/pull/598/commits/e32838259272d3004a60288e3b4c53c5b64a3edd)

2021-04-22 00:59 UTC, PeteCoward commented on src/riot/WagtailPages/LessonPage.riot.html
> +                    : undefined;
see [fix lesson page](https://github.com/catalpainternational/canoe/pull/598/commits/79a5ef013ba117b3ad6065950668faef184936a9)

2021-04-22 00:59 UTC, PeteCoward commented on src/riot/Lesson/TestPopupModal.riot.html
> +                clearPageTestAnswers(this.lesson.id);
see fix [test popup modal](https://github.com/catalpainternational/canoe/pull/598/commits/e32838259272d3004a60288e3b4c53c5b64a3edd)
Which moves completely away from the props.lesson to just use the page get attribute

2021-04-22 01:00 UTC, PeteCoward commented on src/riot/WagtailPages/LessonPage.riot.html
>              <div if="{state.cardImageUrl}" class="lesson-page-image-wrap">
see [fix lesson page](https://github.com/catalpainternational/canoe/pull/598/commits/79a5ef013ba117b3ad6065950668faef184936a9)

2021-04-22 01:00 UTC, PeteCoward commented
Thanks @megganeturner hugely appreciate your review on this!

2021-04-22 01:13 UTC, megganeturner approved these changes
Nice one Peter! This looks good to me

2021-04-22 01:50 UTC, merged