Teaching Activity completion persistance
catalpainternational/canoe pull request #634
Opened 2021-04-23 08:26 UTC by PeteCoward

This uses the `page.complete` mechanism to query and set completion of Teaching Activities.

When `page.complete` is set to true the mechanism built into all `Page` instances in previous PRs, stores the completion in idb, sends it to the api ( which will resync if offline when you come back online ) and sets redux state.
When you get `page.complete` you read from redux state.
On initial page load we read from the api into idb and from idb into redux state.

I may extend this to do similar completion type operations to those we have in Courses, a Course is complete when all Lessons are complete etc...

2021-04-29 17:53 UTC, katevoss commented on src/riot/Teaching/LongCard.riot.html
> +            <!-- <progress
Why is this here but commented out?

2021-04-29 18:21 UTC, katevoss requested changes
I marked a Teaching activity as complete, refreshed the page, and it was incomplete again. I also don't see any entries in my actions IndexedDB

https://user-images.githubusercontent.com/2395211/116599326-f1ac8000-a8f5-11eb-80e9-1ce5738500e8.mov

2021-05-03 00:57 UTC, PeteCoward commented on src/riot/Teaching/LongCard.riot.html
> +            <!-- <progress
I wasn't sure if we wanted it in the long card, but I wanted to make sure it supported it. I can remove

2021-05-06 05:47 UTC, PeteCoward commented
I merged latest, and removed the commented out code
I see your screencapture, and raise you mine. It works fine on my machine.

https://user-images.githubusercontent.com/1092029/117247524-5d07cc00-ae79-11eb-8505-8cc263c6b67b.mov


Will be on https://pep-staging.temp.build for your review too

2021-05-06 17:57 UTC, katevoss approved these changes

2021-05-07 00:04 UTC, merged