Social learning minor tweaks
catalpainternational/canoe pull request #674
Opened 2021-05-12 04:02 UTC by md8n

# Description

Some minor tweaks / refactorings for social learning / discussions.

* Prettier cleanups
* URL registration with the Service Worker
* Update refs for uuid and prettier
* Move some functionality from the discussion riot pages and JS to TS

## Notes
The TS class members could all be made static
The Typings for the discussion stuff are not yet done, but they can now be plugged into the correct places easily

2021-05-13 02:31 UTC, PeteCoward commented on src/riot/Components/DiscussionComment.riot.html
> +            },
There risk with getting/setting state on mount in riot is that it does not execute on update, here it seems to be more of an initialisation that anything else, and if so would fit better in a `state: {...}` initialization like the component initialisation on line 57

2021-05-13 02:31 UTC, PeteCoward commented on src/riot/Components/DiscussionComment.riot.html
> +            },
We should really be accessing the Discussion object from the Lesson object eventually

2021-05-13 02:38 UTC, PeteCoward requested changes
prettier fails
```
ERROR in src/ts/CertChain.ts:32:35
prettier/prettier: Delete `⏎·······················`
    30 |                 const lastError = await this.PostPackageCertificateForSigning();
    31 |                 if (!lastError && this.#packageCert) {
  > 32 |                     const result =
       |                                   ^
  > 33 |                         await this.PostPackageCertificateToAppelflap();
       | ^^^^^^^^^^^^^^^^^^^^^^^^
    34 |                     if (!result) {
    35 |                         this.#packageCert =
    36 |                             await this.GetPackageCertificateFromAppelflap();

ERROR in src/ts/CertChain.ts:35:44
prettier/prettier: Delete `⏎···························`
    33 |                         await this.PostPackageCertificateToAppelflap();
    34 |                     if (!result) {
  > 35 |                         this.#packageCert =
       |                                            ^
  > 36 |                             await this.GetPackageCertificateFromAppelflap();
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    37 |                     }
    38 |                 }
    39 |             }

ERROR in src/ts/tests/AppelflapConnect.test.ts:414:14
prettier/prettier: Insert `⏎···········`
    412 |
    413 |     const unsignedTestResult: TCertificate = {
  > 414 |         cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsakNDQVgrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFQTVEwd0N3WURWUVFERXdSeWNrdFlNQjRYRFRjd01ERXcKTVRBd01EQXdNRm9YRFRRNE1ERXdNVEF3TURBd01Gb3dEekVOTUFzR0ExVUVBeE1FY25KTFdEQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMQk1TQXNaWHk2c05uUzBoenVDb1ZTd05USDVVVEN4bk54WFZ3RkFxREZOVVFrL0dBdDZidDM3CmZMYi9TWUcwTnB5NlJHa295dDlELzhtUy9FNG5GUnV0RXU4ekhJam9mR2JqTXp3clZUNDVlUU5aNmtVSU80MGJXU3Y3UXFsZG53STIKdXU5d0lPNGF1OTdzUEhtSXZXaWRpMm1lcmFoRzFsemQ4VEI1cnRRc0JoN2JKdnJYYTNONUpDN1BLK0Y0aEplclUxWERPWFpNVFFtdAorL2dKMzhxMGFaTVl0Z2xOVTZRVjVwUkh1Y1RKTW45Q09iNTBIQ3BJbDlmdDZIazM4M3MyNWJGVmVGWlQwQVRHenlLOVhvZ0t1Z2hjClRLQzNjNXJlUlljZk9yQlRScTFsRE1yclBzQURyWjZMWUtDcmkvTG5hZ2hyeEIrNmlCK1FuRTBDMTBFQ0F3RUFBVEFOQmdrcWhraUcKOXcwQkFRc0ZBQU1DQUFBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t",
        |              ^
    415 |         isCertSigned: false,
    416 |     };
    417 |     const unsignedCertResponse = new Response(unsignedTestResult.cert, {
```

2021-05-13 05:54 UTC, megganeturner commented on src/ts/Discussion.ts
> +}
Very nice! This file makes `canoe/src/js/DiscussionUtilities.js` redundant, so you can delete that one (:

2021-05-17 00:28 UTC, md8n commented on src/riot/Components/DiscussionComment.riot.html
> +            },
True - As stated in the comments this could be converted to a static class, with static methods, so I'll take that approach instead.

2021-05-17 00:28 UTC, md8n commented on src/ts/Discussion.ts
> +}
Where do you think the code for `discussion.ts` came from :-)

2021-05-17 01:08 UTC, md8n commented on src/riot/Components/DiscussionComment.riot.html
> +            },
Done

2021-05-17 01:09 UTC, md8n commented on src/ts/Discussion.ts
> +}
Done

2021-05-18 01:16 UTC, PeteCoward approved these changes

2021-05-18 01:16 UTC, merged