url cleanup + pageType + manifest cacheKey
catalpainternational/canoe pull request #744
Opened 2021-06-10 02:37 UTC by md8n

# Description

Legacy code used `fullUrl` and `api_url` members to identify where to get resources from, and under what name to save them in the cache.

Over time `fullUrl` was mostly changed  to just `url`.  Also the structure of the `Page` related information within the `Manifest` was standardised, including the usage of `api_url`.

This :pr: :

* Cleans up the `PageType` type to provide better typing support, obviously this includes the `api_url` member.  With the consistency in the manifest this reliably works, and ensures that TypeScript can provide significantly better 'compile' time type support.
* The `PublishableItem` abstract base class is slightly refactored to make much better use of `api_url` and define a better `url`.  The refactoring was to pivot the code from `url` to `api_url`, which is a better fit for its usage in cache interactions.
* `Asset` has special handling for `api_url` so this was refactored to match.
* `Manifest` had its `fullUrl` member removed (it's not used).  Because api_url and cacheKey are interrelated the `ManifestCacheKey` was also updated at this time from `canoe-manifest` to `bero-manifest`.
* `CacheItem` had all of its references to `fullUrl` replaced with `url`.  However it should be noted that most of this code is already deprecated and will likely disappear very soon.

2021-06-10 02:53 UTC, PeteCoward commented on src/ts/Implementations/CacheItem.ts
> - * The item must have a valid `fullUrl`
I'm not sure we have a use for any code in this file anymore, can you explain why we need it?

2021-06-10 02:54 UTC, PeteCoward commented on src/ts/Implementations/PublishableItem.ts
> +    abstract get api_url(): string;
the assets are not retrieved from an API, hence the change to `url`

2021-06-10 05:05 UTC, PeteCoward requested changes
review naming as discussed in slack

2021-06-10 10:32 UTC, md8n commented on src/ts/Implementations/CacheItem.ts
> - * The item must have a valid `fullUrl`
As per slack - I want it to be a :pr: on its own when it comes to deleting this file.

2021-06-11 01:49 UTC, PeteCoward approved these changes

2021-06-11 01:49 UTC, merged