Use singletons and statics to avoid `globalThis` (and flinging an AppelflapConnect object around everywhere)
catalpainternational/canoe pull request #752
Opened 2021-06-15 09:40 UTC by md8n

# Description

# precursor to #751 

Prior to fixing up the handling of the package publishing certificate (certChain) when the user logs in and logs out, it seemed prudent to clean up some old and rather verbose code.

Converted to Singletons (and removed as globals accessed via `globalThis`):
* AppelflapConnect
* BeroHost
* CertChain

Converted to `static` classes (all methods are static):
* CachePublish
* CacheSubscribe
* CacheUtilties

Which meant that all of the following could be simplified, especially as there is no longer any need to pass around an `AppelflapConnect` object or set up globals:
* index.js
* Sync.riot.html
* AppDataStatus
* StartUp
* ItemActions

And also the AppelflapConnect.test file was fixed up - try `yarn test` it works.

2021-06-15 23:46 UTC, PeteCoward commented on src/index.js
>  InitialiseBeroHost();
I'd really prefer to do this in app.js

2021-06-15 23:49 UTC, PeteCoward requested changes
failed to compile
```
ERROR in src/ts/Appelflap/AppelflapConnect.ts:37:1
prettier/prettier: Delete `····`
    35 |             const gt = globalThis as Record<string, any>;
    36 |             gt["AFC_MOCKMODE"] = gt["AFC_MOCKMODE"] || false;
  > 37 |
       | ^^^^
```

2021-06-15 23:57 UTC, PeteCoward commented on src/index.js
>  InitialiseBeroHost();
no need to change that here though

2021-06-16 00:06 UTC, md8n commented
> failed to compile
> 
> ```
> ERROR in src/ts/Appelflap/AppelflapConnect.ts:37:1
> prettier/prettier: Delete `····`
>     35 |             const gt = globalThis as Record<string, any>;
>     36 |             gt["AFC_MOCKMODE"] = gt["AFC_MOCKMODE"] || false;
>   > 37 |
>        | ^^^^
> ```

Fixed - Thanks `prettier`

2021-06-16 00:07 UTC, md8n commented on src/index.js
>  InitialiseBeroHost();
I was thinking of a little review of this stuff as a part of fixing #751 , because it is a reasonable to do so with fixing that issue

2021-06-16 01:45 UTC, PeteCoward approved these changes

2021-06-16 02:27 UTC, merged