Partial fix, but usable-ish
catalpainternational/canoe pull request #774
Opened 2021-06-25 07:04 UTC by md8n

# Description

This matches the changes to the subscription API as described in the docs.

A separate :pr: will cover actually ensuring it works with Appelflap

2021-06-25 10:51 UTC, boerwastaken requested changes
Note that any `map` type in [the relevant descriptor classes](https://github.com/catalpainternational/appelflap/blob/master/koekoek/src/main/java/org/nontrivialpursuit/ingeblikt/Descriptors.kt#L74:L92) may be empty.

Are you sure that's reflected in your types and tests?

2021-06-25 10:51 UTC, boerwastaken commented on src/ts/AppDataStatus.ts
> +        let origins = Object.keys(subscriptions.types.CACHE.groups);
There may not always be a `CACHE` key. Is that caught somewhere?
Note that any `map` type in [the relevant descriptor classes](https://github.com/catalpainternational/appelflap/blob/master/koekoek/src/main/java/org/nontrivialpursuit/ingeblikt/Descriptors.kt#L74:L92) may be empty.

2021-06-25 10:51 UTC, boerwastaken commented on src/ts/tests/AppelflapConnect.test.ts
> +        types: {
I'd recommend also throwing a SWORK type in here. And to test the empty map too.

2021-06-30 01:06 UTC, PeteCoward commented
I may regret asking, but what is [SWORK](https://www.urbandictionary.com/define.php?term=swork)?

2021-06-30 01:11 UTC, md8n commented
> I may regret asking, but what is [SWORK](https://www.urbandictionary.com/define.php?term=swork)?

I'm guessing an abbreviation for Service Worker

2021-06-30 01:11 UTC, md8n commented on src/ts/tests/AppelflapConnect.test.ts
> +        types: {
done

2021-06-30 01:12 UTC, md8n commented on src/ts/AppDataStatus.ts
> +        let origins = Object.keys(subscriptions.types.CACHE.groups);
done

2021-06-30 01:12 UTC, md8n commented
> Are you sure that's reflected in your types and tests?

It is now

2021-06-30 06:43 UTC, boerwastaken commented
> >  I may regret asking, but what is SWORK?

> I'm guessing an abbreviation for Service Worker

Youse _could_ grep the docs, ya know.

2021-06-30 23:56 UTC, merged