866 sync sharing versions
catalpainternational/canoe pull request #869
Opened 2021-07-22 05:33 UTC by md8n

# Description

This sets the 'min' values used in defining subscriptions to what should hopefully be correct values.

2021-07-22 06:05 UTC, boerwastaken commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
I'm not sure - would you really want to have a version of a page injected that your current manifest might not be aware of (since from its perspective, it's "from the future")? **Gathering** and **redistributing** it (through `p2p_version_*` seems like a good proactive behaviour, but having it injected willy nilly?

I don't think we want behaviour that the webapp sans Appelflap would not exhibit. In webapp sans Appelflap land, last time I looked at it, the following invariant holds: the version of the manifest is never lower than the versions of any of the things it refers to.

2021-07-22 06:09 UTC, boerwastaken commented
I think I might need to overhaul this subscriptions API, to make it more fine-grained and to make it easier to handle "co-authoring" it.

2021-07-22 08:22 UTC, PeteCoward commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
We definitely do not want a version of anything newer than the latest manifest tell us it should be.

2021-07-22 08:24 UTC, PeteCoward commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
Ideally the manifest tells Bero we need Page Y version X, Bero tells Appelflap it needs Page Y Version X, Appelflap only delivers Page Y version X.
Bero when it has manifest version Z should be telling Appelflap that it needs Manifest version >Z though.

2021-07-22 11:06 UTC, boerwastaken commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
For the injections, yes.
For the p2p bundle acquisition/redistribution, it'd be very wise to enter Page Y Version X+N, with N some reasonable number, for reasons outlined elsewhere.

2021-07-22 23:45 UTC, md8n commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
Thanks for restating the comments here.  I originally used the version (date) ranges for everything simply to get something shared, because they weren't being shared otherwise.

2021-07-22 23:46 UTC, md8n commented on src/ts/Implementations/ItemActions.ts
>              item.version + (item.type === "manifest" ? aYear : aDay);
Now that we can see sharing happening consistently (and other bad things that were occasionally happening have stopped happening) I think it's a really good time to go back and revisit these numbers exactly as per your comments above.

2021-07-23 00:50 UTC, PeteCoward reviewed
I really do not understand the use of a day and a year here.

What makes sense in my head is...

For the manifest item:
Subscribe for my version + 1 , no maximum
For a page cache:
Subscribe to the version my current manifest tells me to and only that

2021-07-23 01:07 UTC, PeteCoward requested changes
Please change the use of `aYear` to either a very large number, Or if the api supports it null for no maximum

2021-07-23 01:18 UTC, PeteCoward requested changes

2021-07-23 01:18 UTC, PeteCoward commented on src/ts/Implementations/ItemActions.ts
> +        const p2pVersionMax = item.version + aDay;
I think this line ( but not the comment ) says that no versions of this item's cache greater than a day newer than the known item version will be looked for or shared. I think this is wrong.
It means that appelflap will not go looking for any version of the manifest newer than a day after the last version it has.

2021-07-23 01:47 UTC, PeteCoward approved these changes

2021-07-23 03:57 UTC, merged